#144 pl/i support for debug and z unit testcase build
IBM/dbb-zappbuild pull request #145
Opened 2021-10-22 14:38 UTC by flpet-ibm

2021-11-05 08:47 UTC, dennis-behm requested changes
Thanks for the contribution Flemming, I have commented on a couple of sections of your implementation. Please feel free to reach out to me.

2021-11-05 08:47 UTC, dennis-behm commented on languages/PLI.groovy
> +	isZUnitTestCase = (props.getFileProperty('pli_testcase', buildFile).equals('true')) ? true : false
Hi @flpet-ibm,

I am missing the definition of `pli_testcase` in the `sample/application-conf/file.properties` file in your PR. Please add that like the `cobol_testcase` and also update the README for it.

2021-11-05 08:47 UTC, dennis-behm commented on languages/PLI.groovy
> +	def compileDebugParms = props.getFileProperty('pli_compileDebugParms', buildFile)
This build property does not exist in the sample as of today - 'samples/application-conf/PLI.properties' .

2021-11-05 08:47 UTC, dennis-behm commented on languages/PLI.groovy
> +	   parms = "DYNAM(DLL)"
While we allow the parms to be file level overwrites, we should manage this property as such in the `samples/application-conf/PLI.properties` : 

`pli_linkEditParms=DYNAM(DLL) :: **/testcase/*.pli`
(https://github.com/IBM/dbb-zappbuild/blob/development/samples/application-conf/PLI.properties#L37)

2021-11-26 17:12 UTC, dennis-behm commented on samples/application-conf/file.properties
> +# Skip creating a load module for these programs as they will be statically linked to other programs
@flpet-ibm Hi Flems, `samples/application-conf/file.properties` should not contain any specific configuration for MortgageApplication. 

I think you have combined the MortgageSample with the **Template** in sample/application-conf/

2021-11-26 19:34 UTC, flpet-ibm commented
I was not aware that I had pushed the changes to the repo 😂 still work in progress 

Sent from my iPhone

> On 26 Nov 2021, at 18.13, Dennis Behm ***@***.***> wrote:
> 
> ﻿
> This Message Is From an External Sender
> This message came from outside your organization.
> @dennis-behm commented on this pull request.
> 
> In samples/application-conf/file.properties:
> 
> > @@ -17,18 +17,17 @@ dbb.scriptMapping = ZunitConfig.groovy :: **/*.bzucfg
>  dbb.scannerMapping = ZUnitConfigScanner :: **/*.bzucfg
>  
>  #
> -# General file level overwrites through DBB Build Properties 
> -# isCICS = true :: **/cobol/member.cbl
> -# isSQL = true :: **/cobol/member.cbl
> -# isMQ = true :: **/cobol/member.cbl
> -
> -# 
> -# Please check for available file property overwrites within samples/application-conf/README.md
> +# Skip creating a load module for these programs as they will be statically linked to other programs
> @flpet-ibm Hi Flems, samples/application-conf/file.properties should not contain any specific configuration for MortgageApplication.
> 
> I think you have combined the MortgageSample with the Template in sample/application-conf/
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
Medmindre andet er angivet ovenfor: / Unless Otherwise Stated Above:
IBM Danmark ApS
Prøvensvej 1
2605 Brøndby, Danmark
CVR nr.: 65305216

2021-12-16 13:35 UTC, dennis-behm commented on build-conf/README.md
> +pli_test_case_srcPDS | Dataset to move COBOL test source files to from USS
COBOL -> PLI

2021-12-16 13:42 UTC, dennis-behm requested changes
@flpet-ibm Just found a typo in the README :-) Can you please fix it. I will merge it into the develop branch right after. Thanks

2021-12-16 15:18 UTC, dennis-behm approved these changes

2021-12-16 15:20 UTC, merged