Simplify obtaining the playbackDependency
IBM/dbb-zappbuild pull request #310
Opened 2023-01-11 12:04 UTC by dennis-behm

This is simplifying the ZUnitConfig.groovy and fixes #309 for the zAppBuild_2_x stream

2023-01-11 12:09 UTC, jbyibm approved these changes
Looks Good

2023-01-11 12:09 UTC, jbyibm approved these changes
Looks Good

2023-01-29 15:08 UTC, drbruce-git requested changes
What was the result of running the automated zAppBuild tests?
Does it make sense to add new test cases for this code change?

2023-02-16 18:18 UTC, drbruce-git approved these changes

2023-02-24 07:32 UTC, merged